---
- name: run show ospf neighbors
  ios_command:
    commands: show ip ospf neighbor
    provider: "{{ ioscli }}"
  register: ospfneighbor_result

- set_fact: ospfneighbor={{ ospfneighbor_result.stdout_lines | to_nice_yaml }}
