---

  - name: Create IOS VRF List configuration 
    ios_config: 
      src: ../../templates/configurations/ios/20_ios_vrf_list.j2
      provider: "{{ ioscli }}" 
    register: global_config_results 