---

- name: Create NXOS Platform FEX Interface configuration 
  nxos_config: 
    src: ../../templates/configurations/nxos/14_nxos_platform_fex_interface.j2
    provider: "{{ nxoscli }}" 
  tags: vlan 
  register: interface_config_results 