---

- name: Create NXOS Platform Port-Channel configuration 
  nxos_config: 
    src: ../../templates/configurations/nxos/15_nxos_platform_port_channel.j2
    provider: "{{ nxoscli }}" 
    timeout: 600
  tags: vlan 
  register: interface_config_results 