---

- name: Create NXOS Global configuration 
  nxos_config: 
    src: ../../templates/configurations/nxos/01_nxos_global.j2
    provider: "{{ nxoscli }}" 
  tags: global
  register: global_config_results 