---

- name: Create NXOS SVI configuration 
  nxos_config: 
    src: ../../templates/configurations/nxos/11_nxos_platform_vlan_interface.j2
    provider: "{{ nxoscli }}" 
  tags: vlan 
  register: svi_config_results 