---

- name: Create NXOS Platform Class Map
  nxos_config: 
    src: ../../templates/configurations/nxos/06_nxos_platform_class_map.j2
    provider: "{{ nxoscli }}" 
  tags: vlan 
  register: acls_config_results 